export default {
  CHANGE_WINDOW_SIZE: 'CHANGE_WINDOW_SIZE',
  UPDATE_TABLES_VALUES: 'UPDATE_TABLES_VALUES',
  CALCULATE_SAVINGS: 'CALCULATE_SAVINGS',
  SET_CALCULATED_DATA: 'SET_CALCULATED_DATA',
};
